defaultKey:
   UPLOAD_DIRECTORY: docs/resume
   CONTENT_PRAISE: cn:newtol:springbootmarkdown:blog:content:praise
   CONTENT_READNUM: cn:newtol:springbootmarkdown:blog:content:readNum
   WEATHER_URL: https://www.tianqiapi.com/api/
   SOUP_KEY: cn:newtol:springbootmarkdown:api:soupKey
   WEATHER_APPID: 19888371
   WEATHER_APPSECRET: 2BpJ9PC6




spring:

  # 模板消息配置
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false


  # redis配置
  redis:
      database: 0
      host: localhost
      password:
      port: 6379
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

  # mysql数据库配置连接
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/mywebsites?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: xxxxx
      password: xxxxxxx
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 日志配置
logging:
  level:
    cn:
      newtol: warn
  path: markdownLog
  pattern:
    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n"
    console: "%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n"

server:
  port: 8080

